
<?php 
		
	$objectManager =  \Magento\Framework\App\ObjectManager::getInstance();        
 
 
$categoryFactory = $objectManager->get('\Magento\Catalog\Model\CategoryFactory');
$categoryHelper = $objectManager->get('\Magento\Catalog\Helper\Category');
$categoryRepository = $objectManager->get('\Magento\Catalog\Model\CategoryRepository');
		$categoryId = 5; // YOUR CATEGORY ID
$category = $categoryFactory->create()->load($categoryId);
 
//var_dump($category->getData());
 
$parentCategories = $category->getParentCategories();
$childrenCategories = $category->getChildrenCategories();
  
//echo "<pre>";print_r($childrenCategories->getData());
//$storeCategories = $categoryHelper->getStoreCategories();
$_outputhelper = $this->helper('\Magento\Catalog\Helper\Category');

?>

	<div class="home-category-section">
	<h2>Products</h2>
	<?php 
	foreach($childrenCategories as $children){
		
		$catId = $children->getId();
		$resource = $objectManager->get('Magento\Framework\App\ResourceConnection');
		$connection = $resource->getConnection();
		$tableName = $resource->getTableName('catalog_category_entity_varchar');
		 $sql = "SELECT `value` FROM ".$tableName. " WHERE `entity_id` = ".$catId." and attribute_id=149";
		$result = $connection->fetchOne($sql);
		 $imgurl = $objectManager->get('Magento\Store\Model\StoreManagerInterface')
                    ->getStore()
                     ->getBaseUrl(\Magento\Framework\UrlInterface::URL_TYPE_MEDIA) . 'catalog/category/' . $result;?> 
	  <?php if(!empty($result)){?>
	<div class="ctg-list">
	<img src="<?php  echo $imgurl ;?>" alt="<?php echo $children->getName();?>" />
	<h3><a href="<?php  echo $children->getUrl();?>"><?php echo $children->getName();?></a></h3>
	</div>
	<?php } }?>
	</div>