<?php
/**
 * Copyright © 2013-2017 Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<script src='https://www.google.com/recaptcha/api.js'></script>
<form class="form contact"
      action="<?php /* @escapeNotVerified */ echo $block->getFormAction(); ?>"
      id="contact-form"
      method="post"
      data-hasrequired="<?php /* @escapeNotVerified */ echo __('* Required Fields') ?>"
      data-mage-init='{"validation":{}}'>
    <fieldset class="fieldset">
        <legend class="legend"><span><?php /* @escapeNotVerified */ echo __('Enquiry Form') ?></span></legend>
		
		<div class="field name required">
        <div class="control">
		<select name="sendto_addr" id="sendto_addr" class="input-text">
			<option value="" selected="selected">Select Branch *</option>
			<option value="1">Criterion Industries VIC</option>
			<option value="2">Criterion Industries NSW</option>
			<option value="3">Criterion Industries WA</option>
		</select>
		</div>
		</div>
        <div class="field name required">
        <div class="control">
        <select name="enquiry_type" id="enquiry_type" class="input-text validate-select">
            <option value=" ">Select Enquiry Type *</option>
            <option value="Product Information">Product Information</option>                            
            <option value="Technical &amp; Installation Advice">Technical &amp; Installation Advice</option>                            
            <option value="Product Availability">Product Availability</option>                            
            <option value="Pricing">Pricing</option>                            
            <option value="Accounts &amp; Billing">Accounts &amp; Billing</option>                            
            <option value="1">Other (please state)</option> 
        </select>
        </div>
        </div>
        <div class="field name required">
            <div class="control">
                <input name="name" id="name" title="<?php /* @escapeNotVerified */ echo __('First Name') ?>" value="<?php echo $block->escapeHtml($this->helper('Magento\Contact\Helper\Data')->getPostValue('name') ?: $this->helper('Magento\Contact\Helper\Data')->getUserName()) ?>" class="input-text" type="text" data-validate="{required:true}" placeholder="<?php /* @escapeNotVerified */ echo __('First Name') ?>"/>
            </div>
        </div>
		<div class="field name required">
            <div class="control">
                <input name="name" id="name" title="<?php /* @escapeNotVerified */ echo __('Last Name') ?>" value="<?php echo $block->escapeHtml($this->helper('Magento\Contact\Helper\Data')->getPostValue('name') ?: $this->helper('Magento\Contact\Helper\Data')->getUserName()) ?>" class="input-text" type="text" data-validate="{required:true}" placeholder="<?php /* @escapeNotVerified */ echo __('Last Name') ?>"/>
            </div>
        </div>
        <div class="field email required"> 
            <div class="control">
                <input name="email" id="email" title="<?php /* @escapeNotVerified */ echo __('Email') ?>" value="<?php echo $block->escapeHtml($this->helper('Magento\Contact\Helper\Data')->getPostValue('email') ?: $this->helper('Magento\Contact\Helper\Data')->getUserEmail()) ?>" class="input-text" type="email" data-validate="{required:true, 'validate-email':true}" placeholder="<?php /* @escapeNotVerified */ echo __('Email *') ?>"/>
            </div>
        </div>
        <div class="field telephone">
            <div class="control">
                <input name="telephone" id="telephone" title="<?php /* @escapeNotVerified */ echo __('Phone Number') ?>" value="<?php echo $block->escapeHtml($this->helper('Magento\Contact\Helper\Data')->getPostValue('telephone')) ?>" class="input-text" type="text" placeholder="<?php /* @escapeNotVerified */ echo __('Phone Number') ?>" />
            </div>
        </div>
        <div class="field comment required">
            <div class="control">
                <textarea name="comment" id="comment" cols="50" rows="5" title="<?php /* @escapeNotVerified */ echo __('Comment') ?>" cols="5" rows="3" data-validate="{required:true}" placeholder="<?php /* @escapeNotVerified */ echo __('Comment *') ?>" class="input-text"><?php echo $block->escapeHtml($this->helper('Magento\Contact\Helper\Data')->getPostValue('comment')) ?></textarea>
            </div>
        </div>

		<div class="field comment required">
            <div class="control">
                <div class="g-recaptcha" data-sitekey="6LcOuS4UAAAAAJv_qyb7Hyea1us2A9G-phrUWLCC"></div>
            </div>
        </div>
        <?php echo $block->getChildHtml('form.additional.info'); ?>
    </fieldset>
    <div class="actions-toolbar">
        <div class="primary">
            <input type="hidden" name="hideit" id="hideit" value="" />
            <button type="submit" title="<?php /* @escapeNotVerified */ echo __('Submit') ?>" class="action submit primary">
                <span><?php /* @escapeNotVerified */ echo __('Submit') ?></span>
            </button>
        </div>
    </div>
</form>
<?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('contact-us-address')->toHtml();?> 