<?php
/**
 * Copyright © 2013-2017 Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
use Magento\Framework\App\Action\Action;

// @codingStandardsIgnoreFile

?>
<?php
/**
 * Product list template
 *
 * @var $block \Magento\Catalog\Block\Product\ListProduct
 */
?>

<script>
function openCatTab(evt, catId) {
    var i, tablinks, subbucat;
	subbucat = document.getElementsByClassName("left-right-both");
	tablinks = document.getElementsByClassName("tablinks");
    for (i = 0; i < tablinks.length; i++) {
		subbucat[i].style.display = "none";
		tablinks[i].className = tablinks[i].className.replace(" active", "");
    }

    document.getElementById('sub-sub-cat-'+catId).style.display = "block";
    evt.currentTarget.className += " active";
}

require(['jquery', 'jquery/ui'], function($){  
     $(document).ready(function() {
		$(".tab button:first").addClass("active");
		$(".left-right-both:first").show();
    }); 
 });

</script>

<?php
$_productCollection = $block->getLoadedProductCollection();

$_helper = $this->helper('Magento\Catalog\Helper\Output');

$catId = $this->getLayer()->getCurrentCategory()->getId();

$subcategories = $this->getLayer()->getCurrentCategory()->getCategories($catId);

$objectManager = \Magento\Framework\App\ObjectManager::getInstance();

 if($catId ==8){ ?>
	<div class="tab">
	<?php 
	$_object_manager = $objectManager->create('Magento\Catalog\Model\Category')->load($catId);
	
	$subcategories = $_object_manager->getChildrenCategories();
	
	foreach($subcategories as $subcategory){
		if($subcategory->getIsActive()){
		$catPart = explode("(", $subcategory->getName());
		$catPart = isset($catPart[0])?$catPart:$subcategory->getName(); ?>
		
		  <button class="tablinks" onclick="openCatTab(event, '<?php echo $subcategory->getId() ?>')"><b><?php echo $catPart[0] ?></b> <br><span><?php echo isset($catPart[1])?'('.$catPart[1]:''; ?></span></button>
	<?php  }  } ?>
	</div>
		<?php foreach($subcategories as $subcategory){
			  if($subcategory->getIsActive()){
			  $subcatAre = $objectManager->create('Magento\Catalog\Model\Category')->load($subcategory->getId()); 
			  
			  $catPart = explode("(", $subcategory->getName());
			  $catPart = isset($catPart[0])?$catPart:$subcategory->getName();
          
			  $subcats = $subcatAre->getChildrenCategories(); ?>
			<div id="sub-sub-cat-<?php echo $subcategory->getId() ?>" style="display:none" class="left-right-both">
				<div class="right-column">
					<ul>
						<?php foreach($subcats as $subcatis)
						{
							$subcat = $objectManager->create('Magento\Catalog\Model\Category')->load($subcatis->getId()); 
							
							$imgurl = $objectManager->get('Magento\Store\Model\StoreManagerInterface')->getStore()
										->getBaseUrl(\Magento\Framework\UrlInterface::URL_TYPE_MEDIA) . 'catalog/category/' . $subcat->getThumbnail();
							
							if ($imgurl) { ?>
								<li>
									<a href="<?php echo $subcatis->getRequestPath() ?>">
                                    <span class="img-section"><img src="<?php echo $imgurl ?>" style="width:200px; height: 200px;" alt="<?php echo $subcat->getName() ?>" /></span>
									<strong><?php echo $subcat->getName() ?></strong></a>
								</li>
							<?php } 
						} ?>
					</ul>
				</div>

				<div class="left-column">
					<h3><?php echo $catPart[0] ?></h3>
					<?php echo $subcatAre->getDescription() ?>
					<div class="subcategory-sidebar-icons">			
						 <div class="single-icon"><img src="<?php echo $this->getViewFileUrl('images/static/partition-icon01.png'); ?>" alt=""></div>

                        <div class="left-icons-section">
                            <ul>
                                <li><img src="<?php echo $this->getViewFileUrl('images/static/partition-icon02.png'); ?>" alt=""></li>
                                <li><img src="<?php echo $this->getViewFileUrl('images/static/partition-icon03.png'); ?>" alt=""></li>
                                <li><img src="<?php echo $this->getViewFileUrl('images/static/partition-icon04.png'); ?>" alt=""></li>
                                <li><img src="<?php echo $this->getViewFileUrl('images/static/partition-icon05.png'); ?>" alt=""></li>
                                <li><img src="<?php echo $this->getViewFileUrl('images/static/partition-icon06.png'); ?>" alt=""></li>
                                <li><img src="<?php echo $this->getViewFileUrl('images/static/partition-icon07.png'); ?>" alt=""></li>
                            </ul>
                        </div>

                        <div class="estimated">
                            <h4>Estimated Sound rating for solid plasterboard walls</h4>
                            <ul>
                                <li>RW 35 (without insulation)</li>
                                <li>RW 40 (with CAB3 Polyester Insulation)</li>
                            </ul>
                            </div>
					</div>
				</div>
			</div>
		<?php } } ?>		
		
	<?php } else { ?>
	
<?php if (!$_productCollection->count()): ?>
    <div class="message info empty"><div><?php /* @escapeNotVerified */ echo __('We can\'t find products matching the selection.') ?></div></div>
<?php else: ?>
    <?php echo $block->getToolbarHtml() ?>
    <?php echo $block->getAdditionalHtml() ?>
    <?php
    if ($block->getMode() == 'grid') {
        $viewMode = 'grid';
        $image = 'category_page_grid';
        $showDescription = false;
        $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
    } else {
        $viewMode = 'list';
        $image = 'category_page_list';
        $showDescription = true;
        $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::FULL_VIEW;
    }
    /**
     * Position for actions regarding image size changing in vde if needed
     */
    $pos = $block->getPositioned();
    ?>
    <div class="products wrapper <?php /* @escapeNotVerified */ echo $viewMode; ?> products-<?php /* @escapeNotVerified */ echo $viewMode; ?>">
        <?php $iterator = 1; ?>
        <ol class="products list items product-items">
            <?php /** @var $_product \Magento\Catalog\Model\Product */ ?>
            <?php foreach ($_productCollection as $_product): ?>
                <?php /* @escapeNotVerified */ echo($iterator++ == 1) ? '<li class="item product product-item">' : '</li><li class="item product product-item">' ?>
                <div class="product-item-info" data-container="product-grid">
                    <?php
                    $productImage = $block->getImage($_product, $image);
                    if ($pos != null) {
                        $position = ' style="left:' . $productImage->getWidth() . 'px;'
                            . 'top:' . $productImage->getHeight() . 'px;"';
                    }
                    ?>
                    <?php // Product Image ?>
                    <a href="<?php /* @escapeNotVerified */ echo $_product->getProductUrl() ?>" class="product photo product-item-photo" tabindex="-1">
                        <?php echo $productImage->toHtml(); ?>
                    </a>
                    <div class="product details product-item-details">
                        <?php
                            $_productNameStripped = $block->stripTags($_product->getName(), null, true);
                        ?>
                        <strong class="product name product-item-name">
                            <a class="product-item-link"
                               href="<?php /* @escapeNotVerified */ echo $_product->getProductUrl() ?>">
                                <?php /* @escapeNotVerified */ echo $_helper->productAttribute($_product, $_product->getName(), 'name'); ?>
                            </a>
                        </strong>
                        <?php echo $block->getReviewsSummaryHtml($_product, $templateType); ?>
                        <?php /* @escapeNotVerified */ echo $block->getProductPrice($_product) ?>
                        <?php echo $block->getProductDetailsHtml($_product); ?>

                        <div class="product-item-inner">
                            <div class="product actions product-item-actions"<?php echo strpos($pos, $viewMode . '-actions') ? $position : ''; ?>>
                                <div class="actions-primary"<?php echo strpos($pos, $viewMode . '-primary') ? $position : ''; ?>>
                                    <?php if ($_product->isSaleable()): ?>
                                        <?php $postParams = $block->getAddToCartPostParams($_product); ?>
                                        <form data-role="tocart-form" action="<?php /* @escapeNotVerified */ echo $postParams['action']; ?>" method="post">
                                            <input type="hidden" name="product" value="<?php /* @escapeNotVerified */ echo $postParams['data']['product']; ?>">
                                            <input type="hidden" name="<?php /* @escapeNotVerified */ echo Action::PARAM_NAME_URL_ENCODED; ?>" value="<?php /* @escapeNotVerified */ echo $postParams['data'][Action::PARAM_NAME_URL_ENCODED]; ?>">
                                            <?php echo $block->getBlockHtml('formkey')?>
                                            <button type="submit"
                                                    title="<?php echo $block->escapeHtml(__('Add to Cart')); ?>"
                                                    class="action tocart primary">
                                                <span><?php /* @escapeNotVerified */ echo __('Add to Cart') ?></span>
                                            </button>
                                        </form>
                                    <?php else: ?>
                                        <?php if ($_product->getIsSalable()): ?>
                                            <div class="stock available"><span><?php /* @escapeNotVerified */ echo __('In stock') ?></span></div>
                                        <?php else: ?>
                                            <div class="stock unavailable"><span><?php /* @escapeNotVerified */ echo __('Out of stock') ?></span></div>
                                        <?php endif; ?>
                                    <?php endif; ?>
                                </div>
                                <div data-role="add-to-links" class="actions-secondary"<?php echo strpos($pos, $viewMode . '-secondary') ? $position : ''; ?>>
                                    <?php if ($addToBlock = $block->getChildBlock('addto')): ?>
                                        <?php echo $addToBlock->setProduct($_product)->getChildHtml(); ?>
                                    <?php endif; ?>
                                </div>
                            </div>
                            <?php if ($showDescription):?>
                                <div class="product description product-item-description">
                                    <?php /* @escapeNotVerified */ echo $_helper->productAttribute($_product, $_product->getShortDescription(), 'short_description') ?>
                                    <a href="<?php /* @escapeNotVerified */ echo $_product->getProductUrl() ?>" title="<?php /* @escapeNotVerified */ echo $_productNameStripped ?>"
                                       class="action more"><?php /* @escapeNotVerified */ echo __('Learn More') ?></a>
                                </div>
                            <?php endif; ?>
                        </div>
                    </div>
                </div>
                <?php echo($iterator == count($_productCollection)+1) ? '</li>' : '' ?>
            <?php endforeach; ?>
        </ol>
    </div>
    <?php echo $block->getToolbarHtml() ?>
    <?php if (!$block->isRedirectToCartEnabled()) : ?>
        <script type="text/x-magento-init">
        {
            "[data-role=tocart-form], .form.map.checkout": {
                "catalogAddToCart": {}
            }
        }
        </script>
    <?php endif; ?>
	<?php endif; } ?>
