<?php
/**
 * Copyright © 2013-2017 Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php
/**
 * New Customer block template
 *
 * @var $block \Magento\Customer\Block\Form\Login\Info
 */
?>
<?php if ($block->getRegistration()->isAllowed()): ?>
<div class="block block-new-customer">
    <div class="block-title">
        <strong id="block-new-customer-heading" role="heading" aria-level="2"><?php /* @escapeNotVerified */ echo __('Create A New Account') ?></strong>
    </div>
    <div class="block-content" aria-labelledby="block-new-customer-heading">
        <p><?php /* @escapeNotVerified */ echo __('Create an account with us and you’ll be able to:') ?></p>
        <ul>
            <li><?php /* @escapeNotVerified */ echo __('Check out faster') ?></li>
            <li><?php /* @escapeNotVerified */ echo __('Access your order history') ?></li>
            <li><?php /* @escapeNotVerified */ echo __('Track new orders') ?></li>
            <li><?php /* @escapeNotVerified */ echo __('Save items to your wishlist') ?></li>
        </ul>
        <div class="actions-toolbar">
            <div class="primary">
                <a href="<?php /* @escapeNotVerified */ echo $block->getCreateAccountUrl() ?>" class="action create primary"><span><?php /* @escapeNotVerified */ echo __('Create an Account') ?></span></a>
            </div>
        </div>
    </div>
</div>
<?php endif; ?>
